#!/usr/bin/env sh

YABAI_BIN="${YABAI_BIN:-$(command -v yabai || true)}"

if [ -z "$YABAI_BIN" ]; then
  exit 0
fi

"$YABAI_BIN" -m config debug_output off
"$YABAI_BIN" -m config external_bar off:0:0
"$YABAI_BIN" -m config menubar_opacity 1.00
"$YABAI_BIN" -m config mouse_follows_focus off
"$YABAI_BIN" -m config focus_follows_mouse off
"$YABAI_BIN" -m config display_arrangement_order default
"$YABAI_BIN" -m config window_origin_display default
"$YABAI_BIN" -m config window_placement second_child
"$YABAI_BIN" -m config window_insertion_point focused
"$YABAI_BIN" -m config window_zoom_persist off
"$YABAI_BIN" -m config window_shadow on
"$YABAI_BIN" -m config window_opacity off
"$YABAI_BIN" -m config window_opacity_duration 0.00
"$YABAI_BIN" -m config active_window_opacity 1.00
"$YABAI_BIN" -m config normal_window_opacity 0.90
"$YABAI_BIN" -m config window_animation_duration 0.00
"$YABAI_BIN" -m config window_animation_easing ease_out_expo
"$YABAI_BIN" -m config insert_feedback_color 0xffd75f5f
"$YABAI_BIN" -m config layout bsp
"$YABAI_BIN" -m config split_type auto
"$YABAI_BIN" -m config auto_balance off
"$YABAI_BIN" -m config split_ratio 0.50

"$YABAI_BIN" -m config mouse_modifier fn
"$YABAI_BIN" -m config mouse_action1 move
"$YABAI_BIN" -m config mouse_action2 resize
"$YABAI_BIN" -m config mouse_drop_action swap

"$YABAI_BIN" -m config top_padding 12
"$YABAI_BIN" -m config bottom_padding 12
"$YABAI_BIN" -m config left_padding 12
"$YABAI_BIN" -m config right_padding 12
"$YABAI_BIN" -m config window_gap 10

"$YABAI_BIN" -m rule --add label=machelm-float-system-settings app="^System Settings$" manage=on
"$YABAI_BIN" -m rule --add label=machelm-float-finder app="^Finder$" manage=on
"$YABAI_BIN" -m rule --add label=machelm-float-activity-monitor app="^Activity Monitor$" manage=off
"$YABAI_BIN" -m rule --add label=machelm-float-archive-utility app="^Archive Utility$" manage=off
"$YABAI_BIN" -m rule --add label=machelm-custom-rule-machelm-custom-rule-9716BFAC-E139-425B-9200-4AA8A8C3CD21-machelm-machelm-custom-rule-9716bfac-e139-425b-9200-4aa8a8c3cd21-machelm app="^MacHelm$" manage=on
